### ISSUE TITLE
Task area shows a big green arrow mark

### ISSUE THREAD

**Issue by vrenjith** [jenkins-contrib-themes/jenkins-material-theme#66]
Any idea why? See attachment.
<img width="325" alt="screen shot 2016-05-17 at 10 24 41 pm" src="https://cloud.githubusercontent.com/assets/2093241/15331290/39cf74be-1c7e-11e6-857a-18f8a20a3aab.png">

**Comment by afonsof** [comment]
The expected behavior is this:
![image](https://cloud.githubusercontent.com/assets/805511/15796962/edb5ba64-29d6-11e6-919e-669c3f81c4a3.png)

Which version are you using?

**Comment by vrenjith** [comment]
The latest that I downloaded using custom image logo.

On Friday, 3 June 2016, Afonso F <notifications@github.com> wrote:

> The expected behavior is this:
> [image: image]
> <https://cloud.githubusercontent.com/assets/805511/15796962/edb5ba64-29d6-11e6-919e-669c3f81c4a3.png>
>
> Which version are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkins-contrib-themes/jenkins-material-theme/issues/66#issuecomment-223730028>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB_wuQPUgEq4r9P0L0_oj4Kj5STUrjpOks5qINzugaJpZM4Ige_T>
> .
>


-- 
Regards,
Renjith

**Comment by afonsof** [comment]
Could you see the number in the right bottom part of the screen?

**Comment by tomasdeml** [comment]
I could fix this issue by commenting out the following parts in the material-.css file:
```css
.task-icon-link[href='/'] img {
    padding: 36px 0 0 36px!important;
    -webkit-filter: brightness(10000);
    filter: brightness(10000)
}
```

```css
.task-link[href='/'] {
    display: none
}
.task-icon-link[href='/'] {
    position: absolute;
    top: 0;
    left: 0;
    background-color: #689f38;
    height: 64px;
    width: 250px;
    z-index: 2;
    padding: 12px
}
```
